version: '3.8'

services:
  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-blihops_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password}
      POSTGRES_DB: ${POSTGRES_DB:-blihops_dev_db}
    ports:
      - '5432:5432'

  redis:
    command: redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy allkeys-lru
    ports:
      - '6379:6379'


